#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the source-backed Fern Examples2 documentation."""

from __future__ import annotations

import argparse
import ast
import inspect
import json
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "fern" / "docs" / "pages" / "examples2"
GENERATOR_PATH = "scripts/generate_example_docs.py"
GENERATED_MARKER = (
    "{/* Generated by scripts/generate_example_docs.py. "
    "Edit the source Python docstrings instead. */}"
)
BACKTICK = chr(96)


@dataclass(frozen=True)
class Page:
    slug: str
    title: str
    description: str
    source: str
    include_source: bool = True
    api_class: str | None = None


PAGES = (
    Page(
        slug="basic-two-peers",
        title="Basic Two-Peer Transfer",
        description="Register tensors, exchange metadata, and run a NIXL READ transfer.",
        source="examples/python/basic_two_peers.py",
    ),
    Page(
        slug="expanded-two-peers",
        title="Expanded Two-Peer Transfer",
        description="Exercise prepared transfers, parallel operations, and notifications.",
        source="examples/python/expanded_two_peers.py",
    ),
    Page(
        slug="gds-direct-storage",
        title="GDS Direct Storage",
        description="Write a DRAM buffer to storage and read it back through GDS.",
        source="examples/python/nixl_gds_example.py",
    ),
    Page(
        slug="partial-metadata",
        title="Partial Metadata Exchange",
        description="Publish partial metadata and retry transfers as metadata arrives.",
        source="examples/python/partial_md_example.py",
    ),
    Page(
        slug="query-memory",
        title="Query Storage Metadata",
        description="Query file metadata through POSIX or MOCK_DRAM backends.",
        source="examples/python/query_mem_example.py",
    ),
    Page(
        slug="remote-storage",
        title="Remote Storage Transfer",
        description="Pipeline storage and network transfers in a client/server example.",
        source="examples/python/remote_storage_example/nixl_p2p_storage_example.py",
    ),
    Page(
        slug="telemetry-reader",
        title="Telemetry Reader",
        description="Read current-format NIXL events from a shared-memory telemetry buffer.",
        source="examples/python/telemetry_reader.py",
    ),
    Page(
        slug="nixl-ep-buffer",
        title="NIXL-EP Buffer API",
        description="Source-generated API documentation for expert-parallel communication.",
        source="examples/device/ep/nixl_ep/buffer.py",
        include_source=False,
        api_class="Buffer",
    ),
)


def yaml_string(value: str) -> str:
    """Return a JSON string, which is also a valid YAML scalar."""
    return json.dumps(value, ensure_ascii=False)


def source_url(path: str) -> str:
    """Return the upstream GitHub URL for a repository-relative source path."""
    return f"https://github.com/ai-dynamo/nixl/blob/main/{path}"


def fenced(language: str, content: str) -> str:
    """Wrap content in a Markdown fence longer than any fence in the content."""
    fence = BACKTICK * 3
    while fence in content:
        fence += BACKTICK
    return f"{fence}{language}\n{content.rstrip()}\n{fence}"


def parse_source(page: Page) -> tuple[str, ast.Module]:
    """Read and parse a configured source file."""
    path = REPO_ROOT / page.source
    source = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source, filename=page.source)
    except SyntaxError as error:
        raise RuntimeError(f"Cannot parse {page.source}: {error}") from error
    if not ast.get_docstring(tree, clean=False):
        raise RuntimeError(f"{page.source} must define a module docstring")
    return source, tree


def function_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Render a function or method signature without its body."""
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"{prefix} {node.name}({ast.unparse(node.args)}){returns}"


def render_symbol(name: str, signature: str, docstring: str, level: int) -> str:
    """Render one documented Python symbol."""
    heading = "#" * level
    return "\n\n".join(
        (
            f"{heading} {name}",
            fenced("python", signature),
            inspect.cleandoc(docstring),
        )
    )


def render_script_api(tree: ast.Module) -> str:
    """Render documented public top-level classes and functions."""
    sections: list[str] = []
    for node in tree.body:
        if not isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name.startswith("_"):
            continue
        docstring = ast.get_docstring(node, clean=False)
        if not docstring:
            continue
        if isinstance(node, ast.ClassDef):
            bases = ", ".join(ast.unparse(base) for base in node.bases)
            signature = f"class {node.name}({bases})" if bases else f"class {node.name}"
        else:
            signature = function_signature(node)
        sections.append(render_symbol(node.name, signature, docstring, 3))
        if isinstance(node, ast.ClassDef):
            for method in node.body:
                if not isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                if method.name.startswith("_") and method.name != "__init__":
                    continue
                method_doc = ast.get_docstring(method, clean=False)
                if not method_doc:
                    continue
                display_name = (
                    "Constructor" if method.name == "__init__" else method.name
                )
                sections.append(
                    render_symbol(
                        display_name,
                        function_signature(method),
                        method_doc,
                        4,
                    )
                )
    if not sections:
        return ""
    return "## Documented entry points\n\n" + "\n\n".join(sections)


def render_class_api(tree: ast.Module, class_name: str) -> str:
    """Render one class and all of its documented public methods."""
    class_node = next(
        (
            node
            for node in tree.body
            if isinstance(node, ast.ClassDef) and node.name == class_name
        ),
        None,
    )
    if class_node is None:
        raise RuntimeError(f"Class {class_name} was not found")

    class_doc = ast.get_docstring(class_node, clean=False)
    if not class_doc:
        raise RuntimeError(f"Class {class_name} must define a docstring")

    bases = ", ".join(ast.unparse(base) for base in class_node.bases)
    class_signature = (
        f"class {class_node.name}({bases})" if bases else f"class {class_node.name}"
    )
    sections = [
        "## API reference",
        render_symbol(class_node.name, class_signature, class_doc, 3),
    ]

    for node in class_node.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name.startswith("_") and node.name != "__init__":
            continue
        docstring = ast.get_docstring(node, clean=False)
        if not docstring:
            continue
        display_name = "Constructor" if node.name == "__init__" else node.name
        sections.append(
            render_symbol(display_name, function_signature(node), docstring, 3)
        )

    return "\n\n".join(sections)


def frontmatter(page: Page) -> str:
    """Render Fern page frontmatter."""
    return "\n".join(
        (
            "---",
            f"title: {yaml_string(page.title)}",
            f"description: {yaml_string(page.description)}",
            "---",
        )
    )


def render_page(page: Page) -> str:
    """Render one source-backed example page."""
    source, tree = parse_source(page)
    module_doc = inspect.cleandoc(ast.get_docstring(tree, clean=False) or "")
    parts = [
        frontmatter(page),
        GENERATED_MARKER,
        module_doc,
        "## Canonical source\n\n" f"[{page.source}]({source_url(page.source)})",
    ]

    if page.api_class:
        parts.append(render_class_api(tree, page.api_class))
    else:
        api = render_script_api(tree)
        if api:
            parts.append(api)

    if page.include_source:
        parts.append(
            "## Complete source\n\n"
            "This code is copied verbatim from the canonical Python example.\n\n"
            + fenced("python", source)
        )

    return "\n\n".join(parts).rstrip() + "\n"


def render_index() -> str:
    """Render the generated Examples2 landing page."""
    rows = [
        "| Page | Canonical source | Purpose |",
        "| --- | --- | --- |",
    ]
    for page in PAGES:
        rows.append(
            f"| {page.title} | "
            f"[{page.source}]({source_url(page.source)}) | "
            f"{page.description} |"
        )

    return (
        "---\n"
        'title: "Examples2"\n'
        'description: "Experimental source-generated documentation for NIXL Python examples."\n'
        "---\n\n"
        f"{GENERATED_MARKER}\n\n"
        "These experimental pages are generated from module, class, and method "
        "docstrings in the canonical Python examples. Pages for executable scripts "
        "also embed the exact source file, so the documentation cannot silently "
        "diverge from the checked-in example.\n\n"
        "The existing Examples section is intentionally unchanged.\n\n"
        + "\n".join(rows)
        + "\n"
    )


def expected_pages() -> dict[Path, str]:
    """Return every generated path and its expected content."""
    pages = {OUTPUT_DIR / "index.md": render_index()}
    pages.update({OUTPUT_DIR / f"{page.slug}.md": render_page(page) for page in PAGES})
    return pages


def generated_files() -> set[Path]:
    """Return files currently owned by this generator."""
    if not OUTPUT_DIR.exists():
        return set()
    owned = set()
    for path in OUTPUT_DIR.glob("*.md"):
        if GENERATED_MARKER in path.read_text(encoding="utf-8"):
            owned.add(path)
    return owned


def check() -> int:
    """Return nonzero when generated files are missing, stale, or unexpected."""
    expected = expected_pages()
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    unexpected = generated_files() - set(expected)

    for path in stale:
        print(f"stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
    for path in sorted(unexpected):
        print(f"unexpected: {path.relative_to(REPO_ROOT)}", file=sys.stderr)

    if stale or unexpected:
        print(f"Run {GENERATOR_PATH} to regenerate Examples2.", file=sys.stderr)
        return 1

    print(f"Examples2 is up to date ({len(expected)} pages).")
    return 0


def write() -> int:
    """Write all generated pages and remove obsolete generator-owned pages."""
    expected = expected_pages()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")

    for path in generated_files() - set(expected):
        path.unlink()

    print(f"Wrote {len(expected)} pages to {OUTPUT_DIR.relative_to(REPO_ROOT)}.")
    return 0


def main() -> int:
    """Parse command-line arguments and generate or check Examples2."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that Examples2 matches the source docstrings",
    )
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
